version: '3.7'

services:
  ovh-ip-updater-go:
    container_name: ovh-ip-updater-go
    image: sazap10/ovh-ip-updater-go
    build: .
    environment:
      - OVH_USERNAME=${OVH_USERNAME}
      - OVH_PASSWORD=${OVH_PASSWORD}
      - DOMAINS=${DOMAINS}
      - SLEEP_DURATION=${SLEEP_DURATION}
    restart: unless-stopped

  lint:
    build: 
      context: .
      target: ci
    command: golangci-lint run -v
