on:
  push:
name: Build, lint and push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Lint code
      run: |
        docker-compose build lint
        docker-compose run lint

  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build image
      run: docker build -t image .

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: set version
      run: |
        echo "PUSH_TYPE=$(echo $GITHUB_REF | cut -d / -f 2)" >> $GITHUB_ENV
        echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

    - name: Push image
      run: |
        IMAGE_ID=sazap10/ovh-ip-updater-go
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag image $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION

    - name: Report build to bugsnag
      uses: sazap10/bugsnag-builds-action@master
      if: env.PUSH_TYPE == 'tags'
      env:
        BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
